language: python
python:
  - "3.6"
branches:
  only:
    - master
install:
  - pip install sphinx sphinx_rtd_theme
script:
  - sphinx-build . _build/html -b html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: "_build/html"
  keep-history: true
  on:
    all_branches: true
