language: python
python:
  - "3.6"
install:
  - pip install sphinx sphinx_rtd_theme
script:
  - make html
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
